#!/bin/bash


echo 'xterm -title "A" -hold -e "./router tableTopology.txt A" & sleep 1
xterm -title "B" -hold -e "./router tableTopology.txt B" & sleep 1
xterm -title "C" -hold -e "./router tableTopology.txt C" & sleep 1
xterm -title "D" -hold -e "./router tableTopology.txt D" & sleep 1
xterm -title "E" -hold -e "./router tableTopology.txt E" & sleep 1
xterm -title "F" -hold -e "./router tableTopology.txt F" & sleep 1 ' | shuf > exec
chmod 777 exec
./exec
rm exec